#!/usr/bin/env python

import sys

from tello_rqt_gui.tello_module import TelloPlugin
from rqt_gui.main import Main

plugin = 'tello_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
