# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelloPlugin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TelloPlugin(object):
    def setupUi(self, TelloPlugin):
        TelloPlugin.setObjectName("TelloPlugin")
        TelloPlugin.resize(978, 762)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/drohne.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TelloPlugin.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(TelloPlugin)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_temperature = QtWidgets.QLabel(TelloPlugin)
        self.label_temperature.setObjectName("label_temperature")
        self.gridLayout.addWidget(self.label_temperature, 5, 3, 1, 1)
        self.label_link = QtWidgets.QLabel(TelloPlugin)
        self.label_link.setObjectName("label_link")
        self.gridLayout.addWidget(self.label_link, 1, 3, 1, 1)
        self.battery_bar = QtWidgets.QProgressBar(TelloPlugin)
        self.battery_bar.setMaximum(100)
        self.battery_bar.setProperty("value", 0)
        self.battery_bar.setObjectName("battery_bar")
        self.gridLayout.addWidget(self.battery_bar, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.link_bar = QtWidgets.QProgressBar(TelloPlugin)
        self.link_bar.setMaximum(90)
        self.link_bar.setProperty("value", 0)
        self.link_bar.setObjectName("link_bar")
        self.gridLayout.addWidget(self.link_bar, 1, 4, 1, 1)
        self.connect_button = QtWidgets.QPushButton(TelloPlugin)
        self.connect_button.setObjectName("connect_button")
        self.gridLayout.addWidget(self.connect_button, 0, 1, 1, 1)
        self.label_bat = QtWidgets.QLabel(TelloPlugin)
        self.label_bat.setObjectName("label_bat")
        self.gridLayout.addWidget(self.label_bat, 0, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(TelloPlugin)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_flight = QtWidgets.QWidget()
        self.tab_flight.setObjectName("tab_flight")
        self.label = QtWidgets.QLabel(self.tab_flight)
        self.label.setGeometry(QtCore.QRect(530, 10, 151, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_flight)
        self.label_2.setGeometry(QtCore.QRect(530, 100, 61, 17))
        self.label_2.setObjectName("label_2")
        self.label_height = QtWidgets.QLabel(self.tab_flight)
        self.label_height.setGeometry(QtCore.QRect(630, 100, 41, 17))
        self.label_height.setObjectName("label_height")
        self.label_4 = QtWidgets.QLabel(self.tab_flight)
        self.label_4.setGeometry(QtCore.QRect(690, 100, 21, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_flight)
        self.label_5.setGeometry(QtCore.QRect(530, 130, 61, 17))
        self.label_5.setObjectName("label_5")
        self.label_speed = QtWidgets.QLabel(self.tab_flight)
        self.label_speed.setGeometry(QtCore.QRect(630, 130, 41, 17))
        self.label_speed.setObjectName("label_speed")
        self.label_7 = QtWidgets.QLabel(self.tab_flight)
        self.label_7.setGeometry(QtCore.QRect(690, 130, 31, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_flight)
        self.label_8.setGeometry(QtCore.QRect(690, 160, 31, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_flight)
        self.label_9.setGeometry(QtCore.QRect(530, 160, 91, 17))
        self.label_9.setObjectName("label_9")
        self.label_flight_time = QtWidgets.QLabel(self.tab_flight)
        self.label_flight_time.setGeometry(QtCore.QRect(630, 160, 41, 17))
        self.label_flight_time.setObjectName("label_flight_time")
        self.label_10 = QtWidgets.QLabel(self.tab_flight)
        self.label_10.setGeometry(QtCore.QRect(530, 190, 91, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_flight)
        self.label_11.setGeometry(QtCore.QRect(690, 190, 51, 17))
        self.label_11.setObjectName("label_11")
        self.label_remaining_time = QtWidgets.QLabel(self.tab_flight)
        self.label_remaining_time.setGeometry(QtCore.QRect(630, 190, 41, 17))
        self.label_remaining_time.setObjectName("label_remaining_time")
        self.label_3 = QtWidgets.QLabel(self.tab_flight)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 171, 51))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.tab_flight)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 151, 17))
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.tab_flight)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 151, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_flight)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_internal_x = QtWidgets.QLabel(self.tab_flight)
        self.label_internal_x.setGeometry(QtCore.QRect(40, 100, 41, 16))
        self.label_internal_x.setObjectName("label_internal_x")
        self.label_internal_y = QtWidgets.QLabel(self.tab_flight)
        self.label_internal_y.setGeometry(QtCore.QRect(110, 100, 41, 16))
        self.label_internal_y.setObjectName("label_internal_y")
        self.label_16 = QtWidgets.QLabel(self.tab_flight)
        self.label_16.setGeometry(QtCore.QRect(90, 100, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_internal_z = QtWidgets.QLabel(self.tab_flight)
        self.label_internal_z.setGeometry(QtCore.QRect(180, 100, 41, 16))
        self.label_internal_z.setObjectName("label_internal_z")
        self.label_18 = QtWidgets.QLabel(self.tab_flight)
        self.label_18.setGeometry(QtCore.QRect(160, 100, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_internal_yaw = QtWidgets.QLabel(self.tab_flight)
        self.label_internal_yaw.setGeometry(QtCore.QRect(270, 100, 41, 16))
        self.label_internal_yaw.setObjectName("label_internal_yaw")
        self.label_19 = QtWidgets.QLabel(self.tab_flight)
        self.label_19.setGeometry(QtCore.QRect(230, 100, 31, 16))
        self.label_19.setObjectName("label_19")
        self.label_slam_x = QtWidgets.QLabel(self.tab_flight)
        self.label_slam_x.setGeometry(QtCore.QRect(40, 190, 41, 16))
        self.label_slam_x.setObjectName("label_slam_x")
        self.label_33 = QtWidgets.QLabel(self.tab_flight)
        self.label_33.setGeometry(QtCore.QRect(90, 190, 16, 16))
        self.label_33.setObjectName("label_33")
        self.label_slam_y = QtWidgets.QLabel(self.tab_flight)
        self.label_slam_y.setGeometry(QtCore.QRect(110, 190, 41, 16))
        self.label_slam_y.setObjectName("label_slam_y")
        self.label_slam_z = QtWidgets.QLabel(self.tab_flight)
        self.label_slam_z.setGeometry(QtCore.QRect(180, 190, 41, 16))
        self.label_slam_z.setObjectName("label_slam_z")
        self.label_34 = QtWidgets.QLabel(self.tab_flight)
        self.label_34.setGeometry(QtCore.QRect(20, 190, 16, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_flight)
        self.label_35.setGeometry(QtCore.QRect(160, 190, 16, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_flight)
        self.label_36.setGeometry(QtCore.QRect(230, 190, 31, 16))
        self.label_36.setObjectName("label_36")
        self.label_slam_yaw = QtWidgets.QLabel(self.tab_flight)
        self.label_slam_yaw.setGeometry(QtCore.QRect(270, 190, 41, 16))
        self.label_slam_yaw.setObjectName("label_slam_yaw")
        self.label_37 = QtWidgets.QLabel(self.tab_flight)
        self.label_37.setGeometry(QtCore.QRect(20, 220, 91, 17))
        self.label_37.setObjectName("label_37")
        self.label_slam_scaling = QtWidgets.QLabel(self.tab_flight)
        self.label_slam_scaling.setGeometry(QtCore.QRect(120, 220, 41, 16))
        self.label_slam_scaling.setObjectName("label_slam_scaling")
        self.label_battery_low = QtWidgets.QLabel(self.tab_flight)
        self.label_battery_low.setGeometry(QtCore.QRect(630, 70, 51, 16))
        self.label_battery_low.setObjectName("label_battery_low")
        self.label_14 = QtWidgets.QLabel(self.tab_flight)
        self.label_14.setGeometry(QtCore.QRect(530, 70, 91, 17))
        self.label_14.setObjectName("label_14")
        self.label_is_flying = QtWidgets.QLabel(self.tab_flight)
        self.label_is_flying.setGeometry(QtCore.QRect(630, 220, 51, 16))
        self.label_is_flying.setObjectName("label_is_flying")
        self.label_15 = QtWidgets.QLabel(self.tab_flight)
        self.label_15.setGeometry(QtCore.QRect(530, 220, 61, 17))
        self.label_15.setObjectName("label_15")
        self.label_47 = QtWidgets.QLabel(self.tab_flight)
        self.label_47.setGeometry(QtCore.QRect(530, 250, 81, 17))
        self.label_47.setObjectName("label_47")
        self.label_fast_mode = QtWidgets.QLabel(self.tab_flight)
        self.label_fast_mode.setGeometry(QtCore.QRect(630, 250, 51, 17))
        self.label_fast_mode.setObjectName("label_fast_mode")
        self.label_fly_mode = QtWidgets.QLabel(self.tab_flight)
        self.label_fly_mode.setGeometry(QtCore.QRect(630, 280, 51, 17))
        self.label_fly_mode.setObjectName("label_fly_mode")
        self.label_48 = QtWidgets.QLabel(self.tab_flight)
        self.label_48.setGeometry(QtCore.QRect(530, 280, 81, 17))
        self.label_48.setObjectName("label_48")
        self.stop_button = QtWidgets.QPushButton(self.tab_flight)
        self.stop_button.setGeometry(QtCore.QRect(20, 350, 55, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.stop_button.setPalette(palette)
        self.stop_button.setObjectName("stop_button")
        self.label_17 = QtWidgets.QLabel(self.tab_flight)
        self.label_17.setGeometry(QtCore.QRect(20, 270, 101, 51))
        self.label_17.setObjectName("label_17")
        self.start_button = QtWidgets.QPushButton(self.tab_flight)
        self.start_button.setGeometry(QtCore.QRect(90, 350, 55, 40))
        self.start_button.setObjectName("start_button")
        self.land_button = QtWidgets.QPushButton(self.tab_flight)
        self.land_button.setGeometry(QtCore.QRect(160, 350, 55, 40))
        self.land_button.setObjectName("land_button")
        self.target_button = QtWidgets.QPushButton(self.tab_flight)
        self.target_button.setGeometry(QtCore.QRect(230, 350, 55, 40))
        self.target_button.setObjectName("target_button")
        self.label_mission_state = QtWidgets.QLabel(self.tab_flight)
        self.label_mission_state.setGeometry(QtCore.QRect(90, 320, 151, 16))
        self.label_mission_state.setObjectName("label_mission_state")
        self.label_20 = QtWidgets.QLabel(self.tab_flight)
        self.label_20.setGeometry(QtCore.QRect(20, 320, 51, 17))
        self.label_20.setObjectName("label_20")
        self.go_home_button = QtWidgets.QPushButton(self.tab_flight)
        self.go_home_button.setGeometry(QtCore.QRect(300, 350, 71, 40))
        self.go_home_button.setObjectName("go_home_button")
        self.tabWidget.addTab(self.tab_flight, "")
        self.tab_console = QtWidgets.QWidget()
        self.tab_console.setObjectName("tab_console")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_console)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.console = QtWidgets.QTextEdit(self.tab_console)
        self.console.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.console.setObjectName("console")
        self.gridLayout_3.addWidget(self.console, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_console, "")
        self.tab_video = QtWidgets.QWidget()
        self.tab_video.setObjectName("tab_video")
        self.label_video = QtWidgets.QLabel(self.tab_video)
        self.label_video.setGeometry(QtCore.QRect(130, 0, 800, 600))
        self.label_video.setObjectName("label_video")
        self.record_button = QtWidgets.QPushButton(self.tab_video)
        self.record_button.setGeometry(QtCore.QRect(20, 40, 61, 61))
        self.record_button.setObjectName("record_button")
        self.foto_button = QtWidgets.QPushButton(self.tab_video)
        self.foto_button.setGeometry(QtCore.QRect(20, 150, 61, 61))
        self.foto_button.setObjectName("foto_button")
        self.label_record_time = QtWidgets.QLabel(self.tab_video)
        self.label_record_time.setGeometry(QtCore.QRect(20, 110, 101, 17))
        self.label_record_time.setObjectName("label_record_time")
        self.label_foto = QtWidgets.QLabel(self.tab_video)
        self.label_foto.setGeometry(QtCore.QRect(20, 220, 101, 17))
        self.label_foto.setObjectName("label_foto")
        self.tabWidget.addTab(self.tab_video, "")
        self.gridLayout.addWidget(self.tabWidget, 7, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cpu = QtWidgets.QLabel(TelloPlugin)
        self.label_cpu.setObjectName("label_cpu")
        self.horizontalLayout.addWidget(self.label_cpu)
        self.cpu_bar = QtWidgets.QProgressBar(TelloPlugin)
        self.cpu_bar.setProperty("value", 24)
        self.cpu_bar.setObjectName("cpu_bar")
        self.horizontalLayout.addWidget(self.cpu_bar)
        self.label_memory = QtWidgets.QLabel(TelloPlugin)
        self.label_memory.setObjectName("label_memory")
        self.horizontalLayout.addWidget(self.label_memory)
        self.memory_bar = QtWidgets.QProgressBar(TelloPlugin)
        self.memory_bar.setProperty("value", 24)
        self.memory_bar.setObjectName("memory_bar")
        self.horizontalLayout.addWidget(self.memory_bar)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.label_sys = QtWidgets.QLabel(TelloPlugin)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_sys.setFont(font)
        self.label_sys.setObjectName("label_sys")
        self.gridLayout.addWidget(self.label_sys, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.temperature_bar = QtWidgets.QProgressBar(TelloPlugin)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setObjectName("temperature_bar")
        self.horizontalLayout_2.addWidget(self.temperature_bar)
        self.label_wifi = QtWidgets.QLabel(TelloPlugin)
        self.label_wifi.setObjectName("label_wifi")
        self.horizontalLayout_2.addWidget(self.label_wifi)
        self.wifi_signal_bar = QtWidgets.QProgressBar(TelloPlugin)
        self.wifi_signal_bar.setMinimum(-90)
        self.wifi_signal_bar.setMaximum(-25)
        self.wifi_signal_bar.setProperty("value", -90)
        self.wifi_signal_bar.setObjectName("wifi_signal_bar")
        self.horizontalLayout_2.addWidget(self.wifi_signal_bar)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(TelloPlugin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TelloPlugin)

    def retranslateUi(self, TelloPlugin):
        _translate = QtCore.QCoreApplication.translate
        TelloPlugin.setWindowTitle(_translate("TelloPlugin", "Flybot"))
        self.label_temperature.setText(_translate("TelloPlugin", "Temp."))
        self.label_link.setText(_translate("TelloPlugin", "Quality"))
        self.link_bar.setFormat(_translate("TelloPlugin", "%v"))
        self.connect_button.setText(_translate("TelloPlugin", "Connect"))
        self.label_bat.setText(_translate("TelloPlugin", "Battery"))
        self.label.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-size:20pt;\">Flight Data</span></p></body></html>"))
        self.label_2.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Height:</span></p></body></html>"))
        self.label_height.setText(_translate("TelloPlugin", "0.0"))
        self.label_4.setText(_translate("TelloPlugin", "m"))
        self.label_5.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Speed:</span></p></body></html>"))
        self.label_speed.setText(_translate("TelloPlugin", "0.0"))
        self.label_7.setText(_translate("TelloPlugin", "m/s"))
        self.label_8.setText(_translate("TelloPlugin", "s"))
        self.label_9.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Flight time:</span></p></body></html>"))
        self.label_flight_time.setText(_translate("TelloPlugin", "0.0"))
        self.label_10.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Remaining:</span></p></body></html>"))
        self.label_11.setText(_translate("TelloPlugin", "min:s"))
        self.label_remaining_time.setText(_translate("TelloPlugin", "0:0"))
        self.label_3.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-size:20pt;\">Position Data</span></p></body></html>"))
        self.label_6.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Internal Positioning:</span></p></body></html>"))
        self.label_12.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">SLAM Positioning:</span></p></body></html>"))
        self.label_13.setText(_translate("TelloPlugin", "x:"))
        self.label_internal_x.setText(_translate("TelloPlugin", "0.0"))
        self.label_internal_y.setText(_translate("TelloPlugin", "0.0"))
        self.label_16.setText(_translate("TelloPlugin", "y:"))
        self.label_internal_z.setText(_translate("TelloPlugin", "0.0"))
        self.label_18.setText(_translate("TelloPlugin", "z:"))
        self.label_internal_yaw.setText(_translate("TelloPlugin", "0.0"))
        self.label_19.setText(_translate("TelloPlugin", "yaw:"))
        self.label_slam_x.setText(_translate("TelloPlugin", "0.0"))
        self.label_33.setText(_translate("TelloPlugin", "y:"))
        self.label_slam_y.setText(_translate("TelloPlugin", "0.0"))
        self.label_slam_z.setText(_translate("TelloPlugin", "0.0"))
        self.label_34.setText(_translate("TelloPlugin", "x:"))
        self.label_35.setText(_translate("TelloPlugin", "z:"))
        self.label_36.setText(_translate("TelloPlugin", "yaw:"))
        self.label_slam_yaw.setText(_translate("TelloPlugin", "0.0"))
        self.label_37.setText(_translate("TelloPlugin", "Scaling facor:"))
        self.label_slam_scaling.setText(_translate("TelloPlugin", "0.0"))
        self.label_battery_low.setText(_translate("TelloPlugin", "False"))
        self.label_14.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Battery low:</span></p></body></html>"))
        self.label_is_flying.setText(_translate("TelloPlugin", "False"))
        self.label_15.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Is flying:</span></p></body></html>"))
        self.label_47.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Fast-Mode:</span></p></body></html>"))
        self.label_fast_mode.setText(_translate("TelloPlugin", "False"))
        self.label_fly_mode.setText(_translate("TelloPlugin", "0"))
        self.label_48.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Fly-Mode:</span></p></body></html>"))
        self.stop_button.setText(_translate("TelloPlugin", "Stop"))
        self.label_17.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-size:20pt;\">Mission</span></p></body></html>"))
        self.start_button.setText(_translate("TelloPlugin", "Start"))
        self.land_button.setText(_translate("TelloPlugin", "Land"))
        self.target_button.setText(_translate("TelloPlugin", "Target"))
        self.label_mission_state.setText(_translate("TelloPlugin", "<html><head/><body><p>waiting</p></body></html>"))
        self.label_20.setText(_translate("TelloPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">State:</span></p></body></html>"))
        self.go_home_button.setText(_translate("TelloPlugin", "Go Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_flight), _translate("TelloPlugin", "Flight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_console), _translate("TelloPlugin", "Console"))
        self.label_video.setText(_translate("TelloPlugin", "TextLabel"))
        self.record_button.setText(_translate("TelloPlugin", "Record"))
        self.foto_button.setText(_translate("TelloPlugin", "Foto"))
        self.label_record_time.setText(_translate("TelloPlugin", "record"))
        self.label_foto.setText(_translate("TelloPlugin", "take foto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_video), _translate("TelloPlugin", "Video"))
        self.label_cpu.setText(_translate("TelloPlugin", "CPU"))
        self.label_memory.setText(_translate("TelloPlugin", "Memory"))
        self.label_sys.setText(_translate("TelloPlugin", "Sys. Util."))
        self.temperature_bar.setFormat(_translate("TelloPlugin", "%v *C"))
        self.label_wifi.setText(_translate("TelloPlugin", "Wi-Fi"))
        self.wifi_signal_bar.setFormat(_translate("TelloPlugin", "%v dBm"))

